general:
  song select mode:
    inactive: 20         # in seconds
  state:
    default: '0'
    song select: '1'
    list:
    # add [Osu!State] or change [OBS Scene Number] here
    #
    # First value is [Osu!State]
    # Second value is [OBS Scene Number]
    #
      5: 0          # Song Select
      7: 0          # Result
      11: 0         # Multi Lobby
      12: 0         # Multi Room
      2: 3          # Playing
    # ↑     ↑
    # osu!  obs 
    # state scene 
    #       number
    #
    # add [Osu!State] acording to this link
    # reference for [Osu!State] (https://github.com/Piotrekol/ProcessMemoryDataFinder/blob/master/OsuMemoryDataProvider/OsuMemoryStatus.cs)
gosumemory:
  uri: ws://127.0.0.1:24050/ws
obs-websocket:
  host: 127.0.0.1
  port: 4444
  password: '111'
  scene:
    0: '[osu] Main Scene'
    1: '[osu] Zoom Main Scene'
    2: '[osu] Leaderboard Main Scene'
    3: '[osu] Fullscreen Main Scene'
